
/*******************************************************************/
/*                                                                 */
/* Copyright (c) 2005-2008 Jasob.com                               */
/*                                                                 */
/* This obfuscated code was created by Jasob 3.1 Trial Version.    */
/* The code may be used for evaluation purposes only.              */
/* To obtain full rights to the obfuscated code you have to        */
/* purchase the license key (http://www.jasob.com/Purchase.html).  */
/*                                                                 */
/*******************************************************************/

aC={pV:function(t,b,L,d){return L*t/d+b;},rH:{xw:function(t,b,L,d){return L*(t/=d)*t*t*t+b},ts:function(t,b,L,d){return-L*((t=t/d-1)*t*t*t-1)+b},xA:function(t,b,L,d){if((t/=d/2)<1)return L/2*t*t*t*t+b;return-L/2*((t-=2)*t*t*t-2)+b}},dL:1,load:1,max:0,t:0,inter:20,bu:0,fR:0,hD:0,iy:{},kM:{},aB:function(channel,aI,aA,ay,duration,cv,hF,co){if(!aC.dL&&channel!='loading'){am(aI,{l:ay.x,t:ay.y,w:ay.w,h:ay.h});dN(aI,ay.a);return;}var z=aC.iy[channel];if(!z){z=new aC.add(aI,duration,cv,hF,co);z.xj=channel;aC.iy[channel]=z;z.cP=aW(aA.x)&& !aW(ay.x)?az(aI.style.left):aA.x;z.cH=aW(aA.y)&& !aW(ay.y)?az(aI.style.top):aA.y;z.hK=aW(aA.w)&& !aW(ay.w)?az(aI.style.width):aA.w;z.hA=aW(aA.h)&& !aW(ay.h)?az(aI.style.height):aA.h;z.ey=aW(aA.a)&& !aW(ay.a)?xi(aI):aA.a;z.ku=z.cP;z.kq=z.cH;z.kR=z.hK;z.jU=z.hA;z.gR=z.ey;}else{aC.cC(z,duration,cv);z.cP=z.ku;z.cH=z.kq;z.hK=z.kR;z.hA=z.jU;z.ey=z.gR}z.dW=aW(ay.x)?z.cP:ay.x;z.cZ=aW(ay.y)?z.cH:ay.y;z.kP=aW(ay.w)?z.hK:ay.w;z.kJ=aW(ay.h)?z.hA:ay.h;z.fI=aW(ay.a)?z.ey:ay.a;aC.max=M.iV(aC.max,z.duration+z.cv);},add:function(aI,duration,cv,hF,co){var z={};z.aI=aI;aC.cC(z,duration,cv);if(typeof(hF)=='function'){z.ci=hF;z.qi=1;}else{z.ci=aC[hF||'rH'][co||'ts']||aC[hF||'rH'];}return z;},cC:function(a,duration,cv){a.duration=duration||500;a.cv=aC.t+(cv||0);a.end=a.cv+a.duration;aC.start();},start:function(){if(!aC.fR){aC.bu=setInterval(aC.ta,aC.inter);aC.fR=1;}},close:function(){if(aC.bu)clearInterval(aC.bu);aC.fR=0;aC.max=0;aC.t=0;aC.iy={};aC.kM={};if(aC.vW){aC.vW();}},fQ:function(channel,ci,cv){aC.kM[channel]={ci:ci,cv:aC.t+cv};aC.max=M.iV(aC.max,aC.t+cv);aC.start()},ta:function(){var z,y,hD=0;aC.t+=aC.inter;y=aC.iy;for(var i in y){z=y[i];if(aC.t<z.end&&(aC.dL||i=='loading')){if(aC.t>=z.cv){z.rv=z.cP==z.dW?z.dW:R(z.ci(aC.t-z.cv,z.cP,z.dW-z.cP,z.duration,z));z.ru=z.cH==z.cZ?z.cZ:R(z.ci(aC.t-z.cv,z.cH,z.cZ-z.cH,z.duration,z));z.rw=z.hK==z.kP?z.kP:R(z.ci(aC.t-z.cv,z.hK,z.kP-z.hK,z.duration));z.qv=z.hA==z.kJ?z.kJ:R(z.ci(aC.t-z.cv,z.hA,z.kJ-z.hA,z.duration));z.gU=z.ey==z.fI?z.fI:z.ci(aC.t-z.cv,z.ey,z.fI-z.ey,z.duration);if(!z.qi){if(z.ku!=z.rv||z.kq!=z.ru||z.kR!=z.rw||z.jU!=z.qv){am(z.aI,{l:z.ku,t:z.kq,w:z.kR,h:z.jU});}if(z.gR!=z.gU){dN(z.aI,z.gU);}}z.ku=z.rv;z.kq=z.ru;z.kR=z.rw;z.jU=z.qv;z.gR=z.gU;}hD++;}else if(aC.t>=z.end|| !aC.dL){if(z.qi){if(z.cP!=z.dW)z.ci(z.duration,z.cP,z.dW-z.cP,z.duration,z);if(z.cH!=z.cZ)z.ci(z.duration,z.cH,z.cZ-z.cH,z.duration,z);}else{am(z.aI,{l:z.dW,t:z.cZ,w:z.kP,h:z.kJ});dN(z.aI,z.fI);}delete aC.iy[i]}}y=aC.kM;for(var i in y){z=y[i];if(aC.t>=z.cv){z.ci();delete aC.kM[i];hD++}}if(aC.t>=aC.max||hD==0)aC.close();aC.hD=hD;}};